### ISSUE TITLE
[Bug] Magisk modules don't get installed.

### ISSUE THREAD

**Issue by galaxy4627** [nitanmarcel/waydroid-magisk#10]
**Describe the bug**
Magisk modules do not work correctly and do not get installed even with the latest magisk delta canary build.

**Expected behavior**
Magisk modules install and run correctly.

**Comment by nitanmarcel** [comment]
Please follow the issue template

**Comment by nitanmarcel** [comment]
Also make sure you ran the setup after installing

**Comment by galaxy4627** [comment]
> Also make sure you ran the setup after installing

Yeah my bad, so the next issue that I'm encountering is that the setup process fails because `su` could not be executed.
```
[galaxy@arch waydroid-magisk]$ sudo waydroid_magisk setup
lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "su"
lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "su"
lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "su"
lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "su"
lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "su"
lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "su"
```

**Comment by nitanmarcel** [comment]
It seems to not be installed successfully. Do a dmesg when see if the logs matches the other issue

**Comment by nitanmarcel** [comment]
Run `sudo dmesg | grep magiskd -A 3` after waydroid booted

**Comment by galaxy4627** [comment]
> Run `sudo dmesg | grep magiskd -A 3` after waydroid booted
> 
> And also try to install again
```
[galaxy@arch waydroid-magisk-installer]$ sudo waydroid_magisk remove
[20:53:39] - INFO - Stopping Waydroid
[20:53:39] - INFO - Removing Magisk Delta
Traceback (most recent call last):
  File "/sbin/waydroid_magisk", line 1148, in <module>
    main()
  File "/sbin/waydroid_magisk", line 1039, in main
    uninstall(restart_after=True)
  File "/sbin/waydroid_magisk", line 832, in uninstall
    os.remove(os.path.join(WAYDROID_DIR, "bootanim.rc.gz"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/waydroid/bootanim.rc.gz'
[galaxy@arch waydroid-magisk-installer]$ sudo waydroid_magisk install
[20:54:12] - INFO - Stopping Waydroid
[20:54:12] - INFO - Downloading Magisk Delta: canary-fdac22ba-delta
[20:54:15] - INFO - Extracting Magisk Delta
[20:54:15] - INFO - Installing Magisk Delta
[20:54:15] - INFO - Backing up bootanim.rc
[20:54:15] - INFO - Patching bootanim.rc
[20:54:15] - INFO - Finishing installation
[20:54:15] - INFO - Done
[20:54:15] - INFO - Run waydroid_magisk setup after waydroid starts again or install Magisk Delta Manager
[galaxy@arch waydroid-magisk-installer]$ sudo waydroid_magisk setup
[20:55:34] - INFO - Restarting Waydroid in 5 (press ^C to cancel)
[20:55:35] - INFO - Restarting Waydroid in 4 (press ^C to cancel)
[20:55:36] - INFO - Restarting Waydroid in 3 (press ^C to cancel)
[20:55:37] - INFO - Restarting Waydroid in 2 (press ^C to cancel)
[20:55:38] - INFO - Restarting Waydroid in 1 (press ^C to cancel)
[20:55:39] - INFO - Stopping Waydroid
[20:55:40] - INFO - Starting Waydroid
[galaxy@arch waydroid-magisk-installer]$ sudo dmesg | grep magiskd -A 3
[galaxy@arch waydroid-magisk-installer]$ 
```

**Comment by galaxy4627** [comment]
Hmm okay, this seems to be a cosmetic thing as modules seem to be working fine, is it possible to make waydroid pass sn with some modification to universal safetynet fix?

**Comment by nitanmarcel** [comment]
Modules should work now ^^

And Waydroid doesn't support safetynet. It needs selinux for that

**Comment by galaxy4627** [comment]
> Modules should work now ^^
> 
> And Waydroid doesn't support safetynet. It needs selinux for that

Is it possible to get SELinux on Waydroid?

**Comment by nitanmarcel** [comment]
> > Modules should work now ^^
> > And Waydroid doesn't support safetynet. It needs selinux for that
> 
> Is it possible to get SELinux on Waydroid?

Yes, but it's broken. You won't be able to install apps. Also magisk doesn't work with selinux on waydroid, yet

https://github.com/waydroid/waydroid/pull/687
