### ISSUE TITLE
Error while installing magisk

### ISSUE THREAD

**Issue by Shaurya-Kalia** [nitanmarcel/waydroid-magisk#11]
**Describe the bug**
when running `sudo waydroid_magisk install` or `sudo waydroid_magisk install --update`, following error occurs:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1448, in connect
    super().connect()
  File "/usr/lib/python3.11/http/client.py", line 942, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/waydroid_magisk", line 1005, in <module>
    main()
  File "/usr/bin/waydroid_magisk", line 895, in main
    magisk_channels = download_json(
                      ^^^^^^^^^^^^^^
  File "/usr/bin/waydroid_magisk", line 107, in download_json
    with urllib.request.urlopen(url) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
```

**To Reproduce**
1. Run `sudo waydroid_magisk install`
2. Enter password

**Expected behavior**
Above error occurs

**Logs**
[03:13:38] - ERROR - Magisk Delta is not installed

**Desktop (please complete the following information):**
 - OS: manjaro
 - Version: 1.2.4
- Waydroid Version: 1.4.1-1

**Additional context**

**Comment by nitanmarcel** [comment]
`urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>`

There's something wrong with your internet connection. Try disabling any global proxy you might have in your system, or vpn depending on what you're using
