### ISSUE TITLE
[BUG] Magisk is not downloadable so it cannot be installed

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [nitanmarcel/waydroid-magisk#22]
**Describe the bug**
I cannot execute magisk installation to waydroid since it cannot find magisk delta apk to download

**To Reproduce**
1. Go to terminal
2. Type sudo waydroid_magisk install --manager
3. See error no 1

Other method
1. Go to terminal
2. Type sudo waydroid_magisk install
3. See error no 2

**Expected behavior**
Successful installation

**Logs**
From `sudo waydroid_magisk log --save`
[18:16:14] - INFO - Stopping Waydroid
[18:16:15] - INFO - Downloading Magisk Delta: canary-0fe46c5a-delta
Traceback (most recent call last):
  File "/usr/bin/waydroid_magisk", line 144, in download_obj
    with urllib.request.urlopen(url) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/waydroid_magisk", line 1148, in <module>
    main()
  File "/usr/bin/waydroid_magisk", line 1030, in main
    install_fnc(arch, bits, magisk_channel, restart_after=True,
  File "/usr/bin/waydroid_magisk", line 693, in install
    download_obj(magisk["magisk"]["link"], tempdir, "magisk-delta.apk")
  File "/usr/bin/waydroid_magisk", line 148, in download_obj
    raise ValueError("Failed to download %s: %s" % (filename, exc.code))
ValueError: Failed to download magisk-delta.apk: 404

**Logs 2**
[18:24:20] - INFO - Downloading Magisk Delta: canary-0fe46c5a-delta
Traceback (most recent call last):
  File "/usr/bin/waydroid_magisk", line 144, in download_obj
    with urllib.request.urlopen(url) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/waydroid_magisk", line 1148, in <module>
    main()
  File "/usr/bin/waydroid_magisk", line 1030, in main
    install_fnc(arch, bits, magisk_channel, restart_after=True,
  File "/usr/bin/waydroid_magisk", line 693, in install
    download_obj(magisk["magisk"]["link"], tempdir, "magisk-delta.apk")
  File "/usr/bin/waydroid_magisk", line 148, in download_obj
    raise ValueError("Failed to download %s: %s" % (filename, exc.code))
ValueError: Failed to download magisk-delta.apk: 404

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 23.10
- Waydroid Version: 1.4.2

**Additional context**

I've used the version of the tool from the deb repository you're hosting

Btw an suggestion: add ability to select custom and forked repos so that we can use forked versions of Magisk Delta if something goes wrong to their official repo

**Comment by nitanmarcel** [comment]
I will update the repository in the next week, if the new magisk from husky will be released

**Comment by YogSottot** [comment]
there is new
https://github.com/HuskyDG/magisk-files/releases

**Comment by nitanmarcel** [comment]
Fixed in the latest commit. If you installed this via the debian repo wait a couple of minutes for everything to build.


Fell free to reopen if something goes wrong.
